modLoader="javafml"
loaderVersion="[38,)"
license="LGPLv3"
issueTrackerURL="https://github.com/CorgiTaco/Dimension-Height-Clamp"
[[mods]]
modId="dimensionheightclamp"
version="${file.jarVersion}"
displayName="Dimension Height Clamp"
displayURL="https://github.com/CorgiTaco/Dimension-Height-Clamp"
authors="Corgi Taco"
description='''
Sets a min/max Y for ALL dimensions.
'''
[[dependencies.dimensionheightclamp]] #optional
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.dimensionheightclamp]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
